---
  - hosts: loadbalancers
    tasks:
    - name: Configure port number
      lineinfile: path=/etc/config.cfg regexp='^port' line='port=80'
      notify: Restart apache

    handlers:
      - name: Restart apache
        service: name=https status=restarted